### ISSUE TITLE
Don't ignore - at the end of queries

### ISSUE THREAD

**Issue by lynn** [uakci/toadua#22] opened 2023-01-06 19:01 UTC
Or at least make scoring aware of it: when I type `% rui-` in Discord I'd want to see `ruı-` over `ruı`.

**Comment by lynn** [comment] 2023-01-06 19:04
Also, searching `mu-rom` should show the definition for mụrom.

**Comment by uakci** [comment] 2023-01-06 20:37
Duplicate of #23 – search taps into the toaq normalization function, so updating it should resolve this issue, too.

**Closed** 2023-01-07 10:13 UTC
